### ISSUE TITLE
Possible to clean up database after malicious insertions?

### ISSUE THREAD

**Issue by snan** [bzg/woof#5]
This looks like an amazing design, but I wonder if there is also a way to clean up the database in case randos foul it up by posting spam etc? Once they learn the magic headers or words they have basically the keys to the kingdom. Which is a good thing 99% of the time but that one time out of a hundred we need to bring out the mop and bucket.

**Comment by bzg** [comment]
Hi @snan, thanks for your idea! The current usage of woof in the wild is https://updates.orgmode.org where emails are only handled when sent through the mailing list, so spam is not a real issue here.

But you're right, spam can be an issue, for example if someone exposes directly the email address to which Woof is hooked.  In that case, just sending an email with the proper header will immediately create an item in the database.

I've added two issues: an for only allowing some email addresses (a whitelist), another for deleting the items of a list of emails (the spam list), which would require launching the script where Woof runs.

I'll also consider ways for the admin to delete stuff by sending an email with `X-Woof-Delete', I need to think about this.

And finally, perhaps some admin would want to be able to validate entries, something that I don't know how to implement yet.

Thanks again for triggering this!

**Comment by snan** [comment]
Yes, not only unsolicited commercial email but also active vandalism can happen. Hopefully not often♥

**Comment by bzg** [comment]
Yes, hopefully :)  Closing this right now as ideas have been stored in other issus.  Thanks again.
